In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split_test_split

In [2]:
datos = np.random.randint(0,100,(100,4))

In [6]:
datos

array([[74, 15, 44, 42],
       [89, 22, 75, 89],
       [60, 80, 80, 43],
       [64, 93, 31, 23],
       [76, 23, 26, 36],
       [ 0, 82, 65, 20],
       [31, 55, 42, 15],
       [74, 23, 73, 64],
       [ 7, 57, 78, 97],
       [76, 67, 59,  0],
       [82, 21,  5, 83],
       [ 5,  9, 11, 93],
       [17, 25,  6, 87],
       [59, 67, 59, 22],
       [65, 34,  0, 57],
       [12, 57, 63, 48],
       [60, 33, 53, 32],
       [39, 55, 63, 98],
       [62, 94, 12, 16],
       [93, 95, 36,  6],
       [22, 21, 93, 91],
       [82, 47, 80, 40],
       [85, 25, 35, 33],
       [37, 54, 78, 10],
       [23, 44, 70, 42],
       [86, 42, 46, 41],
       [13,  0, 85, 55],
       [29, 23, 73,  9],
       [58, 95, 25,  2],
       [ 4, 28, 58, 99],
       [ 0, 90, 88, 59],
       [58, 55, 68, 79],
       [53, 50, 46, 16],
       [40, 57, 99, 73],
       [58, 53, 61,  0],
       [ 7, 60, 13, 57],
       [68,  3, 38, 46],
       [94, 53, 37, 29],
       [34, 93, 24, 32],
       [67, 44, 46, 35],
       [29, 94, 62, 21],
       [42, 52, 98, 18],
       [79, 49, 79, 18],
       [58, 98, 87,  4],
       [56, 40, 51, 16],
       [71, 12, 23, 53],
       [59, 34, 42, 70],
       [39, 22, 37, 10],
       [36, 87, 84, 24],
       [52, 76, 48, 70],
       [54, 97, 49, 97],
       [68, 73, 97, 73],
       [73, 57, 52, 91],
       [14, 11, 62, 86],
       [20, 51, 47,  5],
       [36, 49, 10, 66],
       [34, 64, 45, 55],
       [ 4, 43, 11, 10],
       [89, 35, 70, 49],
       [ 5, 50, 77, 71],
       [63, 78, 68,  5],
       [32, 53, 33, 75],
       [24, 28,  2, 76],
       [63, 58, 86, 36],
       [98, 61, 98, 34],
       [25, 73, 16, 25],
       [29, 56,  4, 41],
       [ 4, 55, 60, 37],
       [95, 15, 97, 49],
       [42, 34, 80, 56],
       [70, 19, 26, 94],
       [88, 34, 29, 99],
       [23, 64, 85, 28],
       [90, 98, 39, 38],
       [64, 19, 36, 41],
       [15,  1, 78, 63],
       [84, 91, 74, 22],
       [29, 93, 80, 91],
       [83,  0, 75,  0],
       [88, 97, 23, 31],
       [45, 38, 54, 75],
       [94, 76, 76, 16],
       [64, 98, 38, 35],
       [13, 67, 77, 13],
       [40, 93, 33, 15],
       [23, 51, 46, 22],
       [66, 52, 69, 74],
       [28, 31, 42,  1],
       [60, 30, 20, 10],
       [ 3, 97, 97, 69],
       [50, 54, 98, 52],
       [20, 83, 87, 79],
       [26, 96, 89, 41],
       [99, 74, 83, 44],
       [13,  8, 18, 58],
       [43, 19, 84, 60],
       [64, 33, 75, 47],
       [54, 25, 32, 84],
       [77, 67, 59, 67],
       [10, 20, 67, 69]])

In [7]:
dataframe = pd.DataFrame(data=datos, columns=['c1','c2','c3','etiqueta'])

In [8]:
dataframe

    c1  c2  c3  etiqueta
0   74  15  44        42
1   89  22  75        89
2   60  80  80        43
3   64  93  31        23
4   76  23  26        36
5    0  82  65        20
6   31  55  42        15
7   74  23  73        64
8    7  57  78        97
9   76  67  59         0
10  82  21   5        83
11   5   9  11        93
12  17  25   6        87
13  59  67  59        22
14  65  34   0        57
15  12  57  63        48
16  60  33  53        32
17  39  55  63        98
18  62  94  12        16
19  93  95  36         6
20  22  21  93        91
21  82  47  80        40
22  85  25  35        33
23  37  54  78        10
24  23  44  70        42
25  86  42  46        41
26  13   0  85        55
27  29  23  73         9
28  58  95  25         2
29   4  28  58        99
..  ..  ..  ..       ...
70  70  19  26        94
71  88  34  29        99
72  23  64  85        28
73  90  98  39        38
74  64  19  36        41
75  15   1  78        63
76  84  91  74        22
77  29  93  80        91
78  83   0  75         0
79  88  97  23        31
80  45  38  54        75
81  94  76  76        16
82  64  98  38        35
83  13  67  77        13
84  40  93  33        15
85  23  51  46        22
86  66  52  69        74
87  28  31  42         1
88  60  30  20        10
89   3  97  97        69
90  50  54  98        52
91  20  83  87        79
92  26  96  89        41
93  99  74  83        44
94  13   8  18        58
95  43  19  84        60
96  64  33  75        47
97  54  25  32        84
98  77  67  59        67
99  10  20  67        69

[100 rows x 4 columns]

In [9]:
x = dataframe[['c1','c2','c3']]

In [10]:
x

    c1  c2  c3
0   74  15  44
1   89  22  75
2   60  80  80
3   64  93  31
4   76  23  26
5    0  82  65
6   31  55  42
7   74  23  73
8    7  57  78
9   76  67  59
10  82  21   5
11   5   9  11
12  17  25   6
13  59  67  59
14  65  34   0
15  12  57  63
16  60  33  53
17  39  55  63
18  62  94  12
19  93  95  36
20  22  21  93
21  82  47  80
22  85  25  35
23  37  54  78
24  23  44  70
25  86  42  46
26  13   0  85
27  29  23  73
28  58  95  25
29   4  28  58
..  ..  ..  ..
70  70  19  26
71  88  34  29
72  23  64  85
73  90  98  39
74  64  19  36
75  15   1  78
76  84  91  74
77  29  93  80
78  83   0  75
79  88  97  23
80  45  38  54
81  94  76  76
82  64  98  38
83  13  67  77
84  40  93  33
85  23  51  46
86  66  52  69
87  28  31  42
88  60  30  20
89   3  97  97
90  50  54  98
91  20  83  87
92  26  96  89
93  99  74  83
94  13   8  18
95  43  19  84
96  64  33  75
97  54  25  32
98  77  67  59
99  10  20  67

[100 rows x 3 columns]

In [11]:
y = dataframe['etiqueta']

In [12]:
y

0     42
1     89
2     43
3     23
4     36
5     20
6     15
7     64
8     97
9      0
10    83
11    93
12    87
13    22
14    57
15    48
16    32
17    98
18    16
19     6
20    91
21    40
22    33
23    10
24    42
25    41
26    55
27     9
28     2
29    99
      ..
70    94
71    99
72    28
73    38
74    41
75    63
76    22
77    91
78     0
79    31
80    75
81    16
82    35
83    13
84    15
85    22
86    74
87     1
88    10
89    69
90    52
91    79
92    41
93    44
94    58
95    60
96    47
97    84
98    67
99    69
Name: etiqueta, Length: 100, dtype: int64

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3)

In [14]:
x_train.shape

(70, 3)

In [15]:
x_test.shape

(30, 3)

In [16]:
y_train.shape

(70,)

In [17]:
y_test.shape

(30,)